name: Check search frontend

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '**'

jobs:
  check-search-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bring system up
        run: |
            set -ex
            cd search
            mkdir -p live-data
            docker-compose up -d
            sleep 1
            while docker-compose ps | grep health:.starting > /dev/null; do sleep 1; done
            (docker-compose ps | grep -q 'elasticsearch.*Up.(healthy)') || (docker-compose ps; docker-compose logs; false)
      - name: Index test data
        run: |
            bash search/scripts/index_test_images.sh
      # TODO: find syntax to run shutdown regardless of previous step outcomes
      - name: Shutdown
        run: |
            cd search
            docker-compose down
