# This is built on GitHub's "basic workflow to help you get started with Actions"

name: JSON validation CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
#  push:
#    branches: 
#      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Compile yaml schema to JSON
        run: |
          pip install pyyaml
          cd schema
          make
          echo {} > test.json
