# This is built on GitHub's "basic workflow to help you get started with Actions"

name: JSON validation CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
#  push:
#    branches: 
#      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Compile yaml schema to JSON
        run: |
          pip install pyyaml
          cd schema
          make
          echo {} > test.json
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - run: npm install -g ajv-cli
      - name: Validate JSON
        run: |
          cd schema
          ajv -s main.json -r '*.json' -d ../conversion_tools/cwfid_to_json/cwfid_imageinfo.json -d ../conversion_tools/deepweeds_to_json/deepweeds_imageinfo.json
