# This is built on GitHub's "basic workflow to help you get started with Actions"

name: JSON validation CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
#  push:
#    branches: 
#      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Compile yaml schema to JSON
        run: |
          pip install pyyaml
          cd schema
          make
      - name: Run import tools on test data
        run: |
          # TODO: use requirements file
          pip install pyyaml pandas humanfriendly tqdm exifread pillow
          cd conversion_tools/cwfid_to_json/
          curl -L https://github.com/cwfid/dataset/archive/36290d0.tar.gz | tar xzv
          mv dataset-36290d0*/* .
          python cwfid_to_json.py
          cd ../deepweeds_to_json
          curl -L https://github.com/AlexOlsen/DeepWeeds/archive/51e3fab.tar.gz | tar xzv
          mv DeepWeeds-51e3fab*/* .
          # fake some images: make them all be a pic from cwfid
          mkdir deepweeds_images_full
          for fname in $(cut -d, -f1 < labels.csv); do ln -s ../../cwfid_to_json/images/001_image.png deepweeds_images_full/$fname; done
          python deepweeds_to_json.py --labels-dir labels --image-dir deepweeds_images_full -o deepweeds_imageinfo.json
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - run: npm install -g ajv-cli
      - name: Validate JSON
        run: |
          cd schema
          ajv -s main.json -r '*.json' -d ../conversion_tools/cwfid_to_json/cwfid_imageinfo.json -d ../conversion_tools/deepweeds_to_json/deepweeds_imageinfo.json
